apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deployment-minikube
spec:
  selector:
    matchLabels:
      app: minikubeapp
  
  template:
    metadata:
      labels:
        app: minikubeapp
    spec:
      containers:
      - name: minikubeapp-ctr
        image: schatur/jenkins-pipeline:tagname
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: minikubeapp-svc
  labels:
    app: minikubeapp
spec:
  type: NodePort
  ports:
    - port: 8075
      targetPort: 8081
      protocol: TCP   
      
  selector:
    app: minikubeapp
